services:
    mydatabase:
        image: mydatabasetest:latest
        container_name: mydatabase
        volumes:
            - ./data_db:/opt/code/source/data
        ports:
            - 8080:8080
